version: 2
jobs:
  build:
    docker:
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/node:latest
      - image: circleci/postgres:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout
      - run:
          command: npm install
      - run: echo "hello world!"

  deploy:
    machine:
        enabled: true
    working_directory: ~/chummy
    environment:
      - HEROKU_APP: yummy-chummy
    steps:
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git remote add heroku https://git.heroku.com/yummy-chummy.git
                wget https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz
                sudo mkdir -p /usr/local/lib /usr/local/bin
                sudo tar -xvzf heroku-linux-amd64.tar.gz -C /usr/local/lib
                sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/local/bin/heroku
                cat > ~/.netrc << 'EOF'
                machine api.heroku.com
                  login $HEROKU_LOGIN
                  password $HEROKU_API_KEY
                machine git.heroku.com
                  login $HEROKU_LOGIN
                  password $HEROKU_API_KEY
                'EOF'
                # Add heroku.com to the list of known hosts
                ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
                git push heroku master
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
